#!/bin/bash

MYDIR=$(pwd)
file=$(basename $1)
rm -f  $MYDIR/GNU-plot-$file
cat >> $MYDIR/GNU-plot-$file << EOF
#-----------------------------------------------------------------------
#       THIS IS A GNUPLOT SCRIPT 
#-----------------------------------------------------------------------
set terminal qt

set xlabel "Timestep"
set ylabel "Energy"
set autoscale
#set yrange [-2000:25000]


#-----------------------------------------------------------------------
#       For LAMMPS log-plots from the MedeA themo stats
#       1 - Step
#	2 - Time
#	3 - Pressure
#	4 - Volume
#	5 - System Density
#	6 - Temperature
#	7-14 - Different energies (bond, angle dihedrals etc.)
#	15 - Potential Energy
#	16 - Kinetic Energy
#-----------------------------------------------------------------------

#------ Energies
#plot for [i=7:14] '$1' using 1:i title columnheader w l, \
#        for [i=15:16] '' using 1:i title columnheader w l, \
#        '' using 1:((\$15+\$16)*0.5) title 'Total Eng' w l, \
#        '' using 1:6 title columnheader w l

plot '$1' using 1:((\$15+\$16)*0.1) title 'Total Eng' w l, \
        '' using 1:(\$15*0.2) title columnheader w l, \
        '' using 1:(\$16*0.2) title columnheader w l, \
        '' using 1:(\$3) title columnheader w l, \
        '' using 1:(\$4*0.1) title columnheader w l, \
        '' using 1:(\$5) title columnheader w l, \
        '' using 1:(\$6) title columnheader w l, \

pause -1
EOF

gnuplot GNU-plot-$file
rm -f  $MYDIR/GNU-plot-$file
