#!/usr/bin/python

#The code extracts atomic positions from the .geom file from CASTEP
import sys

#open file as first parameter
seedname = str(sys.argv[1]) # First argument is a CASTEP seedname

#read in the file 
f=open(seedname+'.geom','r')
geomlines = f.readlines()
f.close

#reverse the file to find the lst positions 
rev_geomlines=geomlines[::-1]

#extract the lines with abs positions of atoms and lattice vectors
block_coords=[]
block_lattice_vec=[]
for line in rev_geomlines:
	if '<-- E' in line:
		break
	if '<-- R' in line:
		block_coords.append(line)
	if '<-- h' in line:
		block_lattice_vec.append(line)
#reverse the coords back as well as lattice vectors
block_coords=block_coords[::-1]
block_lattice_vec=block_lattice_vec[::-1]

#extract only the atom species and positions, change the coords to angstroms
coords=[]
changer=0.5291772109217
for atom in block_coords:
	species=atom.split()[0]
	pos_x=float(atom.split()[2])*changer
	pos_y=float(atom.split()[3])*changer
	pos_z=float(atom.split()[4])*changer
	coords.append(species+'\t'+str(pos_x)+'\t'+str(pos_y)+'\t'+str(pos_z)+'\n')

#extract only the values for the lattice vectors
lattice_vec=[]
for vector in block_lattice_vec:
	vec_x=float(vector.split()[0])*changer
	vec_y=float(vector.split()[1])*changer
	vec_z=float(vector.split()[2])*changer
	lattice_vec.append(str(vec_x)+'\t'+str(vec_y)+'\t'+str(vec_z)+'\n')


#read in the .cell file to get the proper format 
h=open(seedname+'.cell','r')
celllines=h.readlines()
h.close()

#look for the atomic positions in the cell file
for line in celllines:
	if '%block positions_abs' in line:
		beg_lineno = celllines.index(line)
	if '%block lattice_cart' in line:
		beg_lattice = celllines.index(line)

#replace the initial atomic positions with the relaxed ones
for i in range(0,(len(coords))):
	celllines[i+beg_lineno+1]=coords[i]

#replace the initial lattice vectors with the relaxed ones
for i in range(0,len(lattice_vec)):
	celllines[i+beg_lattice+2]=lattice_vec[i]


#print out to new relaxed file 
g=open('relaxed_'+seedname+'.cell','w')
g.writelines(celllines)
g.close
