#!/bin/bash

MYDIR=$(pwd)
file=$(basename $1)

LIST="3 (\$4*0.1) 5 6 (\$15*0.2) (\$16*0.2)"

rm -f  $MYDIR/GNU-plot-$file
cat >> $MYDIR/GNU-plot-$file <<EOF
#-----------------------------------------------------------------------
#       THIS IS A GNUPLOT SCRIPT 
#-----------------------------------------------------------------------
set terminal qt

set xlabel "Timestep"
set ylabel "Energy"
set autoscale
#set yrange [-2000:25000]


#-----------------------------------------------------------------------
#       For LAMMPS log-plots from the MedeA themo stats
#       1 - Step
#	2 - Time
#	3 - Pressure
#	4 - Volume
#	5 - System Density
#	6 - Temperature
#	7-14 - Different energies (bond, angle dihedrals etc.)
#	15 - Potential Energy
#	16 - Kinetic Energy
#-----------------------------------------------------------------------


plot '$1' using 1:((\$15+\$16)*0.1) title 'Total Eng' w l, \\
EOF

for index in $LIST
do
echo "		'' using 1:$index title columnheader w l, \\" >> $MYDIR/GNU-plot-$file
done

echo -e  "\npause -1" >> $MYDIR/GNU-plot-$file

gnuplot GNU-plot-$file
rm -f  $MYDIR/GNU-plot-$file
