#!/bin/bash

MYDIR=$(pwd)
file=$(basename $1)
rm -f  $MYDIR/GNU-plot-$file
cat >> $MYDIR/GNU-plot-$file << EOF
#-----------------------------------------------------------------------
#       THIS IS A GNUPLOT SCRIPT 
#-----------------------------------------------------------------------
set terminal qt

set xlabel "Timestep"
set ylabel "Energy"
set autoscale
#set yrange [-2000:25000]


#-----------------------------------------------------------------------
#       For LAMMPS log-plots from the MedeA themo stats
#       Pot Eng - 15
#       Kin Eng - 16
#       Rest energies - 7-14
#       Temp - 6
#-----------------------------------------------------------------------

plot for [i=7:14] '$1' using 1:i title columnheader w lp, \
        for [i=15:16] '' using 1:i title columnheader w lp, \
        '' using 1:((\$15+\$16)*0.5) title 'Total Eng' w lp linewidth 2, \
        '' using 1:6 title columnheader w lp

pause -1
EOF

gnuplot GNU-plot-$file
rm -f  $MYDIR/GNU-plot-$file
